version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
  app1:
    container_name: app1
    build: ./app1
    ports:
      - 8080:8080
    volumes:
      - ./app1:/app
    environment:
      - PORT=8080
      - KKAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic1

  app2:
    container_name: app2
    build: ./app2
    ports:
      - 8081:8080
    volumes:
      - ./app2:/app
    environment:
      - PORT=8081
      - KKAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic2

  app3:
    container_name: app3
    build: ./app3
    ports:
      - 8082:8080
    volumes:
      - ./app3:/app
    environment:
      - PORT=8082
      - KKAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC1=topic1
      - KAFKA_TOPIC2=topic2
  
  app4:
    container_name: app4
    build: ./app4
    ports:
      - 8083:8080
    volumes:
      - ./app4:/app
    environment:
      - PORT=8083
      - MONGO_URL=mongodb://mongo:27017/app2
      - KKAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic2
